.TH LCG 1
.SH NAME
lcg \- convert data structure by logistic map
.SH SYNOPSIS
\fBlcg\fR [\fI-s\fR][\fI-k KEYFILE\fR] SOURCE DEST\fR
.br
.de FL
.TP
\\fB\\$1\\fR
\\$2
..
.de EX
.TP 20
\\fB\\$1\\fR
# \\$2
..
.SH EXAMPLES
.P
\fBlcg input.bin output.bin\fP                   Encode binary file
.P
\fBlcg -d input.bin output.bin\fP                Decode binary file
.P
\fBlcg -k key.bin input.bin output.bin\fP        Encrypt binary file
.P
\fBlcg -d -k key.bin input.bin output.bin\fP     Decrypt binary file
.SH DESCRIPTION
.PP
.I Lcg
uses logistic mapping for bit string generation and data hiding.
.SH AUTHOR
.I Lcg
is written by Hideto Manjo.
.SH COPYLIGHT
Copyright (C) 2019  Hideto Manjo.
.br
.I Lcg
is released under the terms of the MIT license.